---
title: "predicted_growth_results"
output: html_document
date: "2025-07-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Project Setup

```{r}
devtools::load_all()
kwm <- clean(klein_waggle_math) |> dplyr::filter(!is.na(outcome))
```


# Run Analysis for Grades K-2

```{r}
run_analysis(kwm |> dplyr::filter(grade_grp == "GK2"), .mod = list("Grades K - 2"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes"),
.terms = list("waggle_math_assignments_completed_sytd"))
```


# Run Analysis for Grades 3-5

```{r}
run_analysis(kwm |> dplyr::filter(grade_grp == "G35"), .mod = list("Grades 3 - 5"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes"),
.terms = list("waggle_math_assignments_completed_sytd"))
```


# Run Analysis for Full Sample (Grades K - 5)

```{r}
run_analysis(kwm, .mod = list("Grades K - 5"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes"),
.terms = list("waggle_math_assignments_completed_sytd"))
```


# Run Analysis by Grade

```{r}
cat(paste("\n-----Results for Grade: ", "K", "-----\n"))
run_analysis(kwm |> dplyr::filter(grade == "K"), .mod = list(paste0("Grade: ", "K")),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes"),
.terms = list("waggle_math_assignments_completed_sytd"))


grades <- c("1", "2", "3", "4", "5")
for (i in seq_along(grades)){
  cat(paste("\n-----Results for Grade: ", i, "-----\n"))
  run_analysis(kwm |> dplyr::filter(grade == i), .mod = list(paste0("Grade: ", i)),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes"),
.terms = list("waggle_math_assignments_completed_sytd"))
}
```
