---
title: "test_script"
output: html_document
date: "2025-07-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Project Setup

```{r}
devtools::load_all()
kwm <- clean(klein_waggle_math) |> dplyr::filter(!is.na(outcome))
```


# Run Linear Model Analysis

```{r}
run_analysis(kwm, .mod = list("full"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes"),
.terms = list("waggle_math_assignments_completed_sytd"))

run_analysis(kwm |> dplyr::filter(grade_grp == "GK2"), .mod = list("full"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes"),
.terms = list("waggle_math_assignments_completed_sytd"))

run_analysis(kwm |> dplyr::filter(grade_grp == "G35"), .mod = list("full"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes"),
.terms = list("waggle_math_assignments_completed_sytd"))
```


# Run Linear Model Analysis

```{r}
run_analysis(kwm |> dplyr::filter(grade_grp == "GK2"), .mod = list("full"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes + grade"),
.terms = list("waggle_math_assignments_completed_sytd"))

run_analysis(kwm |> dplyr::filter(grade_grp == "G35"), .mod = list("full"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes + grade"),
.terms = list("waggle_math_assignments_completed_sytd"))
```


# Run Mixed Model Analysis

```{r}
run_analysis_mixed(kwm |> dplyr::filter(grade_grp == "GK2"), .mod = list("full"),
.rhs = list("waggle_math_assignments_completed_sytd + waggle_math_session_count_sytd + waggle_math_total_time_sytd_minutes + grade + (1|school_pid)"),
.terms = list("waggle_math_assignments_completed_sytd"))
```

